// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAMoXXWgjghBDnzxJG3umZ5JXUP38SgdY',
    appId: '1:914243259256:web:ea777b3157b3c89d26d68d',
    messagingSenderId: '914243259256',
    projectId: 'pantryscanner-dca28',
    authDomain: 'pantryscanner-dca28.firebaseapp.com',
    storageBucket: 'pantryscanner-dca28.appspot.com',
    measurementId: 'G-JQWB6N6N1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9BXfpkWdee73glyW4aUiurA458uRY37Y',
    appId: '1:914243259256:android:3bb3e4c56c3ee43826d68d',
    messagingSenderId: '914243259256',
    projectId: 'pantryscanner-dca28',
    storageBucket: 'pantryscanner-dca28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPeMzFIKfEALCC6I27654N2TxCYPUUoSk',
    appId: '1:914243259256:ios:2281664d1cca37c326d68d',
    messagingSenderId: '914243259256',
    projectId: 'pantryscanner-dca28',
    storageBucket: 'pantryscanner-dca28.appspot.com',
    iosBundleId: 'com.example.pantryScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPeMzFIKfEALCC6I27654N2TxCYPUUoSk',
    appId: '1:914243259256:ios:2281664d1cca37c326d68d',
    messagingSenderId: '914243259256',
    projectId: 'pantryscanner-dca28',
    storageBucket: 'pantryscanner-dca28.appspot.com',
    iosBundleId: 'com.example.pantryScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAMoXXWgjghBDnzxJG3umZ5JXUP38SgdY',
    appId: '1:914243259256:web:ea5d9615fb7ae38326d68d',
    messagingSenderId: '914243259256',
    projectId: 'pantryscanner-dca28',
    authDomain: 'pantryscanner-dca28.firebaseapp.com',
    storageBucket: 'pantryscanner-dca28.appspot.com',
    measurementId: 'G-QKRFVWYYKQ',
  );
}
